---
language: ruby
cache: bundler
script: bundle exec rake

jobs:
  include:
    - rvm: 2.4.10
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.7.1
    - rvm: 2.7.1
      script: bundle exec rubocop

branches:
  only:
    - master
